declare const Illustrations: {
    Category: string;
    Confetti: string;
    DropShipping: string;
    Easy: string;
    ExperienciaYservicios: string;
    Flex: string;
    Forbidden: string;
    Fullfilment: string;
    FulfillmentByParis: string;
    FulfillmentMarketplace: string;
    InternalServerError: string;
    LostClouds: string;
    MaintenanceError: string;
    NotFound: string;
    OpenBox: string;
    TimeCapsule: string;
    Truck: string;
};
export default Illustrations;
